name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter_svg: ^2.0.17
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/vectors/
    - assets/images/

  fonts:
      - family: CircularStd
        fonts:
          - asset: assets/fonts/CircularStd-Black.ttf
            weight: 800
          - asset: assets/fonts/CircularStd-Bold.ttf
            weight: 700
          - asset: assets/fonts/CircularStd-Medium.ttf
            weight: 500
          - asset: assets/fonts/CircularStd-Regular.ttf
            weight: 400


